# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-28 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='attachments/'),
        ),
    ]
