# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_auto_20180629_0623"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="uploads"),
        ),
    ]
