# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-01 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='add',
            new_name='ad',
        ),
    ]
